site_name: Rosanna's Portfolio
nav:
    - Overview: index.md
#        - Open Library API reasoning
#    - Open Library API: 
#        - Quick-start guide: quickstartguide.md
#       - Search Endpoint Reference: open-lib-book-api.md
    - Open Library Book Search API:
        - Rate limits: rate-limits.md
        - Reference: open-lib-book-api.md
    - AO3 Quick-Start Guide : end-user-guide.md
# test    
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html